apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: APP_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
      - name: APP_NAME
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 30m
        image: gcr.io/PROJECT_ID/APP_NAME:VERSION
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2


---
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: APP_NAME
  type: NodePort
